// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_vENnxasW1uSzPweZfAlSZSziw8T9f8',
    appId: '1:831572355430:web:213f5564649c8b135240a7',
    messagingSenderId: '831572355430',
    projectId: 'unsaid-b61d0',
    authDomain: 'unsaid-b61d0.firebaseapp.com',
    storageBucket: 'unsaid-b61d0.firebasestorage.app',
    measurementId: 'G-D5LW2NXVSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApppPZOFVq2PpCDezWXImkTIs9yEijDo',
    appId: '1:831572355430:android:ef77fc0b66f3ae915240a7',
    messagingSenderId: '831572355430',
    projectId: 'unsaid-b61d0',
    storageBucket: 'unsaid-b61d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQDyjjnFyg2GMbLAKtKliKMao_6HELSbU',
    appId: '1:831572355430:ios:05a983cbe9436fa05240a7',
    messagingSenderId: '831572355430',
    projectId: 'unsaid-b61d0',
    storageBucket: 'unsaid-b61d0.firebasestorage.app',
    iosBundleId: 'com.example.unsaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQDyjjnFyg2GMbLAKtKliKMao_6HELSbU',
    appId: '1:831572355430:ios:05a983cbe9436fa05240a7',
    messagingSenderId: '831572355430',
    projectId: 'unsaid-b61d0',
    storageBucket: 'unsaid-b61d0.firebasestorage.app',
    iosBundleId: 'com.example.unsaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt_vENnxasW1uSzPweZfAlSZSziw8T9f8',
    appId: '1:831572355430:web:213f5564649c8b135240a7',
    messagingSenderId: '831572355430',
    projectId: 'unsaid-b61d0',
    authDomain: 'unsaid-b61d0.firebaseapp.com',
    storageBucket: 'unsaid-b61d0.firebasestorage.app',
    measurementId: 'G-D5LW2NXVSN',
  );
}
